name: movie_recommender_system
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  - pandas
  - ydata-profiling
  - dvc-s3
  - nltk
  - scikit-learn
  - streamlit
  - pip:
    - -e ."[dev]"
